# Generated by Django 2.1 on 2018-08-07 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd_category', models.CharField(choices=[('life', 'life'), ('IN', 'insurance'), ('APPLE', 'appleid'), ('STA', 'staff'), ('GA', 'game'), ('WO', 'work'), ('BA', 'bank'), ('PH', 'phone'), ('GIT', 'git'), ('MA', 'machine'), ('OT', 'others')], default='life', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_id', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('middle_comments', models.CharField(blank=True, max_length=200)),
                ('text_repeat', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('first_comments', models.CharField(blank=True, max_length=200)),
                ('second_comments', models.CharField(blank=True, max_length=200)),
                ('third_comments', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 7, 14, 44, 33, 221618), verbose_name='date published')),
                ('validation', models.BooleanField(blank=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytool.Category')),
            ],
        ),
    ]
