# Generated by Django 2.1 on 2018-08-07 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pwd_category',
            field=models.CharField(choices=[('LIFE', 'life'), ('INSURANCE', 'insurance'), ('APPLEID', 'appleid'), ('STAFF', 'staff'), ('GAME', 'game'), ('WORK', 'work'), ('BANK', 'bank'), ('PHONE', 'phone'), ('GIT', 'git'), ('MACHINE', 'machine'), ('OTHERS', 'others')], default='LIFE', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='category',
            field=models.ForeignKey(choices=[('LIFE', 'life'), ('INSURANCE', 'insurance'), ('APPLEID', 'appleid'), ('STAFF', 'staff'), ('GAME', 'game'), ('WORK', 'work'), ('BANK', 'bank'), ('PHONE', 'phone'), ('GIT', 'git'), ('MACHINE', 'machine'), ('OTHERS', 'others')], default=('LIFE', 'life'), on_delete=django.db.models.deletion.CASCADE, to='mytool.Category'),
        ),
        migrations.AlterField(
            model_name='password',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 7, 15, 23, 59, 793732), verbose_name='date published'),
        ),
    ]
