# Generated by Django 2.1 on 2018-08-07 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytool', '0002_auto_20180807_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytool.Category'),
        ),
        migrations.AlterField(
            model_name='password',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 7, 15, 35, 51, 972400), verbose_name='date published'),
        ),
    ]
