# Generated by Django 2.1 on 2018-08-07 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytool', '0003_auto_20180807_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 7, 15, 54, 22, 388844), verbose_name='date published'),
        ),
    ]
